dns:
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.tbank.ru'
  - tbank.ru
  default-nameserver:
  - 77.88.8.8
  - 77.88.8.1
  nameserver:
  - https://common.dot.dns.yandex.net/dns-query
  - 77.88.8.8
  - 77.88.8.1
sniffer:
  enable: true
  force-domain:
  - +.max.ru
  sniff:
    TLS:
      ports:
      - 443
      - 8443
    HTTP:
      ports:
      - 80
      - 8080
proxies:
- name: 🇩🇪 Германия | YT без рекламы
  type: vless
  server: de.api-yandex.net
  port: 443
  network: tcp
  udp: true
  tls: true
  servername: de.api-yandex.net
  reality-opts:
    public-key: NLARt-womsWqopLrSLNpfp3bHXy3Pg08_LbFUQPhpjU
    short-id: 0f4dacf82203e11f
  client-fingerprint: qq
  uuid: 959b4df5-15bc-4eb8-8b93-95f6af50cd80
  packet-encoding: xudp
  flow: xtls-rprx-vision
- name: 🇸🇪 Швеция | YT без рекламы
  type: vless
  server: sw.api-yandex.net
  port: 443
  network: tcp
  udp: true
  tls: true
  servername: sw.api-yandex.net
  reality-opts:
    public-key: pU7ElcbPMVObHoWqGThioVD4i5ux_phWFwElN97aDSQ
    short-id: 0f4dacf89993e21f
  client-fingerprint: qq
  uuid: 959b4df5-15bc-4eb8-8b93-95f6af50cd80
  packet-encoding: xudp
  flow: xtls-rprx-vision
- name: 🇱🇹 Литва | YT без рекламы
  type: vless
  server: lt.api-yandex.net
  port: 443
  network: tcp
  udp: true
  tls: true
  servername: lt.api-yandex.net
  reality-opts:
    public-key: q_5Tfp_XKPzQdOtiLkVePVMQE6UVAV9xK_WxTULcJSA
    short-id: 00011cf66101e75f
  client-fingerprint: qq
  uuid: 959b4df5-15bc-4eb8-8b93-95f6af50cd80
  packet-encoding: xudp
  flow: xtls-rprx-vision
- name: 🇫🇮 Финляндия | YT без рекламы
  type: vless
  server: fl.api-yandex.net
  port: 443
  network: tcp
  udp: true
  tls: true
  servername: fl.api-yandex.net
  reality-opts:
    public-key: jm1tsCkTKsXunYTjcdHLu_whRQRkZWlWdGbSFDVyREw
    short-id: 0f4dacf89993e11f
  client-fingerprint: qq
  uuid: 959b4df5-15bc-4eb8-8b93-95f6af50cd80
  packet-encoding: xudp
  flow: xtls-rprx-vision
- name: 🇵🇱 Польша | YT без рекламы
  type: vless
  server: pl.api-yandex.net
  port: 443
  network: tcp
  udp: true
  tls: true
  servername: pl.api-yandex.net
  reality-opts:
    public-key: I4lUR4e9kgCZUY_yd2vY_nOcLw0B-e-CNOQxgBgAJn8
    short-id: 0f4dacf88252e05f
  client-fingerprint: qq
  uuid: 959b4df5-15bc-4eb8-8b93-95f6af50cd80
  packet-encoding: xudp
  flow: xtls-rprx-vision
- name: 🇷🇺 Россия | YT без рекламы
  type: vless
  server: ru.api-yandex.net
  port: 443
  network: tcp
  udp: true
  tls: true
  servername: ru.api-yandex.net
  reality-opts:
    public-key: jm1tsCkTKsXunYTjcdHLu_whRQRkZWlWdGbSFDVyREw
    short-id: 0f4dacf89993e20f
  client-fingerprint: qq
  uuid: 959b4df5-15bc-4eb8-8b93-95f6af50cd80
  packet-encoding: xudp
  flow: xtls-rprx-vision
- name: 🇦🇹 Австрия
  type: vless
  server: at.api-yandex.net
  port: 443
  network: tcp
  udp: true
  tls: true
  servername: at.api-yandex.net
  reality-opts:
    public-key: hfJagZHzXLZaHqiyy59ZwnPFytw9WUMu1RGh29o3aVE
    short-id: 2f4dacf62222e15f
  client-fingerprint: qq
  uuid: 959b4df5-15bc-4eb8-8b93-95f6af50cd80
  packet-encoding: xudp
  flow: xtls-rprx-vision
- name: 🇳🇱 Нидерланды
  type: vless
  server: nlbr.api-yandex.net
  port: 443
  network: tcp
  udp: true
  tls: true
  servername: nlbr.api-yandex.net
  reality-opts:
    public-key: 86QxRUvBk3_xNQqwHoyW2MrkNm9eEhbR2uirSnWHkW4
    short-id: 6f4dacf88292e06f
  client-fingerprint: qq
  uuid: 959b4df5-15bc-4eb8-8b93-95f6af50cd80
  packet-encoding: xudp
  flow: xtls-rprx-vision
- name: 🇺🇸 США
  type: vless
  server: us.api-yandex.net
  port: 443
  network: tcp
  udp: true
  tls: true
  servername: us.api-yandex.net
  reality-opts:
    public-key: jA_Xd8qfMloJg0lbdxPnEcDJc3MltgueXpxYQAWnlD0
    short-id: 0f4dacf66101e05f
  client-fingerprint: qq
  uuid: 959b4df5-15bc-4eb8-8b93-95f6af50cd80
  packet-encoding: xudp
  flow: xtls-rprx-vision
- name: 🇬🇧 Великобритания
  type: vless
  server: gb-most.api-yandex.net
  port: 443
  network: tcp
  udp: true
  tls: true
  servername: gb-most.api-yandex.net
  reality-opts:
    public-key: vrBTRg3Wz1K_fxfk8B-lWS7ZUGwxCbeBUgTcWOkSqRY
    short-id: 0fdfdcf08722a04f
  client-fingerprint: qq
  uuid: 959b4df5-15bc-4eb8-8b93-95f6af50cd80
  packet-encoding: xudp
  flow: xtls-rprx-vision
- name: 🇸🇬 Сингапур
  type: vless
  server: sg.api-yandex.net
  port: 443
  network: tcp
  udp: true
  tls: true
  servername: sg.api-yandex.net
  reality-opts:
    public-key: bS0sniF87mp40JiHO6fEuNZmv0ZyHxu55ulj41pL038
    short-id: 0f4dacf62201e05f
  client-fingerprint: qq
  uuid: 959b4df5-15bc-4eb8-8b93-95f6af50cd80
  packet-encoding: xudp
  flow: xtls-rprx-vision
- name: 🇯🇵Япония
  type: vless
  server: jp.api-yandex.net
  port: 443
  network: tcp
  udp: true
  tls: true
  servername: jp.api-yandex.net
  reality-opts:
    public-key: IOO3P6BDqBjUA0gB4tgpvxrXL6Fit88QgpJ1y6GYyz0
    short-id: 0f4dacf88202e05f
  client-fingerprint: qq
  uuid: 959b4df5-15bc-4eb8-8b93-95f6af50cd80
  packet-encoding: xudp
  flow: xtls-rprx-vision
- name: 🇸🇪 Швеция • Gaming 🎮
  type: vless
  server: sw.api-yandex.net
  port: 443
  network: tcp
  udp: true
  tls: true
  servername: sw.api-yandex.net
  reality-opts:
    public-key: pU7ElcbPMVObHoWqGThioVD4i5ux_phWFwElN97aDSQ
    short-id: 0f4dacf89993e21f
  client-fingerprint: qq
  uuid: 959b4df5-15bc-4eb8-8b93-95f6af50cd80
  packet-encoding: xudp
  flow: xtls-rprx-vision
- name: 🇫🇮 Финляндия • Gaming 🎮
  type: vless
  server: fl.api-yandex.net
  port: 443
  network: tcp
  udp: true
  tls: true
  servername: fl.api-yandex.net
  reality-opts:
    public-key: jm1tsCkTKsXunYTjcdHLu_whRQRkZWlWdGbSFDVyREw
    short-id: 0f4dacf89993e11f
  client-fingerprint: qq
  uuid: 959b4df5-15bc-4eb8-8b93-95f6af50cd80
  packet-encoding: xudp
  flow: xtls-rprx-vision
proxy-groups:
- name: 🌍 VPN
  type: select
  proxies:
  - 📺 WiFi YouTube Fallback
  - 📶 WiFi
  - DIRECT
  - 🇩🇪 Германия | YT без рекламы
  - 🇸🇪 Швеция | YT без рекламы
  - 🇱🇹 Литва | YT без рекламы
  - 🇫🇮 Финляндия | YT без рекламы
  - 🇵🇱 Польша | YT без рекламы
  - 🇷🇺 Россия | YT без рекламы
  - 🇦🇹 Австрия
  - 🇳🇱 Нидерланды
  - 🇺🇸 США
  - 🇬🇧 Великобритания
  - 🇸🇬 Сингапур
  - 🇯🇵Япония
  - 🇸🇪 Швеция • Gaming 🎮
  - 🇫🇮 Финляндия • Gaming 🎮
- name: 🔀 VPN_DIRECT
  type: select
  proxies:
  - DIRECT
  - 📺 WiFi YouTube Fallback
  - 📶 WiFi
  - 🇩🇪 Германия | YT без рекламы
  - 🇸🇪 Швеция | YT без рекламы
  - 🇱🇹 Литва | YT без рекламы
  - 🇫🇮 Финляндия | YT без рекламы
  - 🇵🇱 Польша | YT без рекламы
  - 🇷🇺 Россия | YT без рекламы
  - 🇦🇹 Австрия
  - 🇳🇱 Нидерланды
  - 🇺🇸 США
  - 🇬🇧 Великобритания
  - 🇸🇬 Сингапур
  - 🇯🇵Япония
  - 🇸🇪 Швеция • Gaming 🎮
  - 🇫🇮 Финляндия • Gaming 🎮
- name: 📺 WiFi YouTube Fallback
  type: fallback
  url: https://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 🇩🇪 Германия | YT без рекламы
  - 🇸🇪 Швеция | YT без рекламы
  - 🇱🇹 Литва | YT без рекламы
  - 🇫🇮 Финляндия | YT без рекламы
  - 🇵🇱 Польша | YT без рекламы
- name: 📶 WiFi
  type: fallback
  url: https://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 🇦🇹 Австрия
  - 🇳🇱 Нидерланды
  - 🇺🇸 США
  - 🇬🇧 Великобритания
  - 🇸🇬 Сингапур
  - 🇯🇵Япония
  - 🇸🇪 Швеция • Gaming 🎮
  - 🇫🇮 Финляндия • Gaming 🎮
rules:
- DOMAIN-SUFFIX,max.ru,DIRECT
- DOMAIN-KEYWORD,app-analytics-services,🌍 VPN
- DOMAIN-KEYWORD,play.googleapis,🌍 VPN
- DOMAIN-KEYWORD,oauth,🌍 VPN
- DOMAIN-KEYWORD,ai.google,🌍 VPN
- DOMAIN-KEYWORD,developerprofiles-pa,🌍 VPN
- DOMAIN-KEYWORD,notebooklm,🌍 VPN
- DOMAIN-KEYWORD,gemini,🌍 VPN
- DOMAIN-KEYWORD,aistudio,🌍 VPN
- DOMAIN-KEYWORD,generativelanguage,🌍 VPN
- DOMAIN-KEYWORD,google.ai,🌍 VPN
- DOMAIN-KEYWORD,google.dev,🌍 VPN
- DOMAIN-KEYWORD,play.google.com,🌍 VPN
- DOMAIN-KEYWORD,clients6,🌍 VPN
- DOMAIN-KEYWORD,googleapis,🌍 VPN
- DOMAIN-KEYWORD,ytimg,🌍 VPN
- DOMAIN-KEYWORD,googlevideo,🌍 VPN
- DOMAIN-KEYWORD,ggpht,🌍 VPN
- DOMAIN-KEYWORD,gstatic,🌍 VPN
- DOMAIN-KEYWORD,youtube-nocookie,🌍 VPN
- DOMAIN-KEYWORD,googleusercontent,🌍 VPN
- DOMAIN-KEYWORD,youtu,🌍 VPN
- DOMAIN-KEYWORD,openai,🌍 VPN
- DOMAIN-KEYWORD,oai,🌍 VPN
- DOMAIN-KEYWORD,gpt,🌍 VPN
- DOMAIN-KEYWORD,anthropic,🌍 VPN
- DOMAIN-KEYWORD,claude,🌍 VPN
- DOMAIN-KEYWORD,datadoghq,🌍 VPN
- DOMAIN-KEYWORD,sentry,🌍 VPN
- DOMAIN-KEYWORD,amazonaws,🌍 VPN
- DOMAIN-KEYWORD,openrouter,🌍 VPN
- DOMAIN-KEYWORD,deepl,🌍 VPN
- DOMAIN-KEYWORD,models.dev,🌍 VPN
- DOMAIN-KEYWORD,influxdata,🌍 VPN
- DOMAIN-KEYWORD,twimg,🌍 VPN
- DOMAIN-KEYWORD,twitter,🌍 VPN
- DOMAIN-KEYWORD,x.com,🌍 VPN
- DOMAIN-KEYWORD,twtrdns,🌍 VPN
- DOMAIN-KEYWORD,twttr,🌍 VPN
- DOMAIN-KEYWORD,steam,🌍 VPN
- DOMAIN-KEYWORD,linkedin,🌍 VPN
- DOMAIN-KEYWORD,licdn,🌍 VPN
- DOMAIN-KEYWORD,spotify,🌍 VPN
- DOMAIN-KEYWORD,scdn,🌍 VPN
- DOMAIN-KEYWORD,notion,🌍 VPN
- DOMAIN-KEYWORD,medium.com,🌍 VPN
- DOMAIN-KEYWORD,twitch,🌍 VPN
- DOMAIN-KEYWORD,ttvnw,🌍 VPN
- DOMAIN-KEYWORD,jtvnw,🌍 VPN
- DOMAIN-KEYWORD,facebook,🌍 VPN
- DOMAIN-KEYWORD,fbcdn,🌍 VPN
- DOMAIN-KEYWORD,fbpigeon,🌍 VPN
- DOMAIN-KEYWORD,fbsbx,🌍 VPN
- DOMAIN-KEYWORD,m.me,🌍 VPN
- DOMAIN-KEYWORD,meta,🌍 VPN
- DOMAIN-KEYWORD,insta,🌍 VPN
- DOMAIN-KEYWORD,igcdn,🌍 VPN
- DOMAIN-KEYWORD,igsonar,🌍 VPN
- DOMAIN-KEYWORD,igtv,🌍 VPN
- DOMAIN-KEYWORD,whatsapp,🌍 VPN
- DOMAIN-KEYWORD,wa.me,🌍 VPN
- DOMAIN-KEYWORD,github,🌍 VPN
- DOMAIN-KEYWORD,vscode,🌍 VPN
- DOMAIN-KEYWORD,n8n,🌍 VPN
- DOMAIN-KEYWORD,greasyfork,🌍 VPN
- DOMAIN-KEYWORD,adspower,🌍 VPN
- DOMAIN-KEYWORD,amazon,🌍 VPN
- DOMAIN-KEYWORD,iherb,🌍 VPN
- DOMAIN-KEYWORD,canva,🌍 VPN
- DOMAIN-KEYWORD,discord,🌍 VPN
- DOMAIN-KEYWORD,patreon,🌍 VPN
- DOMAIN-KEYWORD,flibusta,🌍 VPN
- DOMAIN-KEYWORD,goodreads,🌍 VPN
- DOMAIN-KEYWORD,gr-assets,🌍 VPN
- DOMAIN-KEYWORD,myheritage,🌍 VPN
- DOMAIN-KEYWORD,paddle,🌍 VPN
- DOMAIN-KEYWORD,slivup,🌍 VPN
- DOMAIN-KEYWORD,sharewood,🌍 VPN
- DOMAIN-KEYWORD,blizzard,🌍 VPN
- DOMAIN-KEYWORD,blz-content,🌍 VPN
- DOMAIN-KEYWORD,sms,🌍 VPN
- DOMAIN-KEYWORD,phncdn,🌍 VPN
- DOMAIN-KEYWORD,pornhub,🌍 VPN
- DOMAIN-KEYWORD,xvideos,🌍 VPN
- DOMAIN-KEYWORD,xv-ru,🌍 VPN
- DOMAIN-KEYWORD,cdn77,🌍 VPN
- DOMAIN-KEYWORD,4pda,🌍 VPN
- DOMAIN-KEYWORD,rutracker,🌍 VPN
- DOMAIN-KEYWORD,rutor,🌍 VPN
- DOMAIN-KEYWORD,nnm,🌍 VPN
- DOMAIN-KEYWORD,stripe,🌍 VPN
- DOMAIN-KEYWORD,ubuntu,🌍 VPN
- DOMAIN-KEYWORD,telegram,🌍 VPN
- DOMAIN-KEYWORD,t.me,🌍 VPN
- IP-CIDR,160.79.104.0/23,🌍 VPN,no-resolve
- IP-CIDR,160.79.104.0/21,🌍 VPN,no-resolve
- IP-CIDR6,2607:6bc0::/48,🌍 VPN,no-resolve
- IP-CIDR,91.108.56.0/22,🌍 VPN,no-resolve
- IP-CIDR,91.108.4.0/22,🌍 VPN,no-resolve
- IP-CIDR,91.108.8.0/22,🌍 VPN,no-resolve
- IP-CIDR,91.108.16.0/22,🌍 VPN,no-resolve
- IP-CIDR,91.108.12.0/22,🌍 VPN,no-resolve
- IP-CIDR,149.154.160.0/20,🌍 VPN,no-resolve
- IP-CIDR,91.105.192.0/23,🌍 VPN,no-resolve
- IP-CIDR,91.108.20.0/22,🌍 VPN,no-resolve
- IP-CIDR,185.76.151.0/24,🌍 VPN,no-resolve
- IP-CIDR6,2001:b28:f23d::/48,🌍 VPN,no-resolve
- IP-CIDR6,2001:b28:f23f::/48,🌍 VPN,no-resolve
- IP-CIDR6,2001:67c:4e8::/48,🌍 VPN,no-resolve
- IP-CIDR6,2001:b28:f23c::/48,🌍 VPN,no-resolve
- IP-CIDR6,2a0a:f280::/32,🌍 VPN,no-resolve
- MATCH,🔀 VPN_DIRECT
